# Generated by Django 4.2.30 on 2026-09-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_tripfaq_triphighlight_tripinclusion_and_more'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='trek',
            field=models.ForeignKey(blank=True, help_text='Set automatically when someone messages from a trek page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='treks.trek'),
        ),
        migrations.CreateModel(
            name='CustomTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('travel_dates', models.CharField(blank=True, help_text="e.g. 'Mid-March 2027' or exact dates", max_length=200)),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('trip_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difficulty_preference', models.CharField(choices=[('no_preference', 'No preference'), ('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult'), ('strenuous', 'Strenuous')], default='no_preference', max_length=20)),
                ('accommodation_preference', models.CharField(choices=[('no_preference', 'No preference'), ('teahouse', 'Teahouse / lodge'), ('hotel', 'Hotel'), ('camping', 'Camping'), ('luxury', 'Luxury lodge')], default='no_preference', max_length=20)),
                ('activity_trekking', models.BooleanField(default=False)),
                ('activity_mountaineering', models.BooleanField(default=False)),
                ('activity_peak_climbing', models.BooleanField(default=False)),
                ('activity_rafting', models.BooleanField(default=False)),
                ('activity_jungle_safari', models.BooleanField(default=False)),
                ('activity_cultural_tour', models.BooleanField(default=False)),
                ('activity_photography', models.BooleanField(default=False)),
                ('activity_helicopter_tour', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_trip_requests', to='treks.trekregion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
