# Generated by Django 4.2.30 on 2026-09-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Adventure Nepal', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Trekking and travel across the Himalayas, guided by locals who know the trails.', max_length=200)),
                ('phone', models.CharField(blank=True, default='+977 9800000000', max_length=30)),
                ('email', models.EmailField(blank=True, default='info@adventurenepal.com', max_length=254)),
                ('address', models.CharField(blank=True, default='Thamel, Kathmandu, Nepal', max_length=255)),
                ('opening_hours', models.CharField(blank=True, default='Sun–Fri, 9:00–18:00 (NPT)', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
