# Generated by Django 4.2.30 on 2026-10-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_highlightitem_newslettersubscriber_sitestatistic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
