# Generated by Django 4.2.30 on 2026-09-27 13:10

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text


def populate_guide_slugs(apps, schema_editor):
    GuideProfile = apps.get_model("accounts", "GuideProfile")

    from django.utils.text import slugify

    used_slugs = set(
        GuideProfile.objects.exclude(slug="").values_list("slug", flat=True)
    )

    for profile in GuideProfile.objects.select_related("user").order_by("id"):
        if profile.slug:
            continue

        base = (
            f"{profile.user.first_name} {profile.user.last_name}".strip()
            or profile.user.username
            or f"guide-{profile.pk}"
        )

        base_slug = slugify(base)[:150]

        if not base_slug:
            base_slug = f"guide-{profile.pk}"

        slug = base_slug
        counter = 2

        while slug in used_slugs:
            suffix = f"-{counter}"
            slug = f"{base_slug[:160 - len(suffix)]}{suffix}"
            counter += 1

        profile.slug = slug
        profile.save(update_fields=["slug"])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_tripfaq_triphighlight_tripinclusion_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guideprofile',
            options={'ordering': ['order', 'user__first_name']},
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck to hide from the public guides pages'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Public profile photo. Falls back to the account avatar if left blank.', null=True, upload_to=apps.accounts.models.SizedUploadTo('guides'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.accounts.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='position',
            field=models.CharField(blank=True, help_text='e.g. Lead Trekking Guide', max_length=100),
        ),
migrations.AddField(
    model_name='guideprofile',
    name='slug',
    field=models.SlugField(
        blank=True,
        max_length=160,
        db_index=False,
    ),
),
migrations.RunPython(
    code=populate_guide_slugs,
    reverse_code=migrations.RunPython.noop,
),
migrations.AlterField(
    model_name='guideprofile',
    name='slug',
    field=models.SlugField(
        blank=True,
        max_length=160,
        unique=True,
    ),
),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.SizedUploadTo('avatars'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.accounts.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='certifications',
            field=models.CharField(blank=True, help_text='Comma-separated. Verify before publishing.', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_useremail_ci_unique'),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='treks.trek'),
        ),
        migrations.AddField(
            model_name='savedtrip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedtrip',
            constraint=models.UniqueConstraint(fields=('user', 'trek'), name='one_save_per_user_per_trek'),
        ),
    ]
