# Generated by Django 4.2.30 on 2026-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='category',
            field=models.CharField(choices=[('trekking', 'Trekking'), ('tour', 'Tour'), ('sightseeing', 'Sightseeing'), ('climbing', 'Climbing')], default='trekking', max_length=20),
        ),
    ]
