# Generated by Django 4.2.30 on 2026-09-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_trek_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trekregion',
            options={'ordering': ['order', 'name'], 'verbose_name': 'destination'},
        ),
        migrations.AddField(
            model_name='trek',
            name='is_popular',
            field=models.BooleanField(default=False, help_text="Show in the homepage 'Popular treks' carousel"),
        ),
        migrations.AddField(
            model_name='trek',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Search-result summary (optional)', max_length=160),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trekregion',
            name='region_type',
            field=models.CharField(choices=[('trek_region', 'Trekking region'), ('city', 'City'), ('park', 'National park')], default='trek_region', max_length=20),
        ),
        migrations.AlterField(
            model_name='trek',
            name='category',
            field=models.CharField(choices=[('trekking', 'Trekking'), ('tour', 'Tour'), ('sightseeing', 'Sightseeing'), ('climbing', 'Climbing'), ('cultural', 'Cultural tour'), ('safari', 'Jungle safari'), ('rafting', 'Rafting'), ('adventure', 'Adventure activity')], default='trekking', max_length=20),
        ),
    ]
