# Generated by Django 4.2.30 on 2026-09-26 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treks', '0003_alter_trekregion_options_trek_is_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TripInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True, help_text="Unchecked = shown under 'What's not included'")),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='trek',
            name='accommodation_summary',
            field=models.CharField(blank=True, help_text='e.g. Teahouses / lodges', max_length=200),
        ),
        migrations.AddField(
            model_name='trek',
            name='altitude_sickness_risk',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trek',
            name='guides',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'guide'}, related_name='guided_treks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trek',
            name='season_autumn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='season_spring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='season_summer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trek',
            name='season_winter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trekitineraryday',
            name='accommodation',
            field=models.CharField(blank=True, help_text='e.g. Teahouse, Hotel, Camping', max_length=100),
        ),
        migrations.AddField(
            model_name='trekitineraryday',
            name='meals',
            field=models.CharField(blank=True, help_text='e.g. Breakfast, Lunch, Dinner', max_length=100),
        ),
        migrations.AddField(
            model_name='trekitineraryday',
            name='walking_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddConstraint(
            model_name='trek',
            constraint=models.CheckConstraint(check=models.Q(('discount_price_usd__isnull', True), ('discount_price_usd__lt', models.F('price_usd')), _connector='OR'), name='trek_discount_lower_than_price'),
        ),
        migrations.AddConstraint(
            model_name='trek',
            constraint=models.CheckConstraint(check=models.Q(('group_size_min__lte', models.F('group_size_max'))), name='trek_min_le_max_group'),
        ),
        migrations.AddConstraint(
            model_name='trek',
            constraint=models.CheckConstraint(check=models.Q(('duration_days__gt', 0)), name='trek_duration_positive'),
        ),
        migrations.AddField(
            model_name='tripinclusion',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='treks.trek'),
        ),
        migrations.AddField(
            model_name='triphighlight',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='treks.trek'),
        ),
        migrations.AddField(
            model_name='tripfaq',
            name='trek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='treks.trek'),
        ),
    ]
